apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
  namespace: projet-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
      - name: fleetman-mongodb
        image: mongo:3.6.23
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db 
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: my-pvc
