apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: projet-kube
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo