apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetman-mongo-pv
  namespace: fleetman
  labels:
    type: local
    app: fleetman-mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/fleetman-mongo