apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: projet-kube
  labels:
    app: my-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi