apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
  namespace: fleetman
  labels:
    app: fleetman-position-tracker
spec:
  selector:
    app: fleetman-position-tracker
  ports:
  - port: 8080
    targetPort: 8080
  