apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: NodePort
  ports:
    - port: 5000        
      targetPort: 80    
      nodePort: 30081   
  selector:
    app: fleetman-webapp