apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
  namespace: fleetman
  labels:
    app: fleetman-mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: fleetman-mongodb