apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  namespace: projet-kube
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: fleetman-api-gateway
  type: ClusterIP
